Update fq.list.yml

diff --git a/.github/workflows/fq.list.yml b/.github/workflows/fq.list.yml
--- a/.github/workflows/fq.list.yml
+++ b/.github/workflows/fq.list.yml
@@ -16,4 +16,11 @@ jobs:
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git add -f fq.list
           git commit -m "Update fq.list"
+      - name: Push changes
+        run: |
           git push --force
+        # Handle errors
+        if [ $? -ne 0 ]; then
+          echo "Error: git push failed"
+          exit 1
+        fi
